name: 'Terrateam Workflow'
description: 'Terraform Automation with GitHub Pull Requests'
inputs:
  work-token:
    description: 'Work token for run'
    required: true
  api-base-url:
    description: 'Base URL to API'
    required: true
    default: 'https://app.terrateam.io'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - '${{ inputs.work-token }}'
    - '${{ inputs.api-base-url }}'
