ARG BASE_IMAGE=ghcr.io/terrateamio/action-base-fips:1789476574@sha256:be1d9f396e8792b534fabe67aba855bb29f6c9b5145c477408b99a4ba5703af4
FROM ${BASE_IMAGE}

COPY entrypoint.sh /entrypoint.sh
COPY entrypoint_gitlab.sh /entrypoint_gitlab.sh
COPY entrypoint_github.sh /entrypoint_github.sh
COPY terrat_runner /terrat_runner

COPY proxy/bin /usr/local/proxy/bin

COPY bin/ /usr/local/bin

ENTRYPOINT ["/entrypoint.sh"]
