ARG BASE_IMAGE=ghcr.io/terrateamio/action-base-fips:1790877483@sha256:39d906b1a645d1c9e677a94e7fda5044dfac074d83b93553bb14bf28cc80ac92
FROM ${BASE_IMAGE}

COPY entrypoint.sh /entrypoint.sh
COPY entrypoint_gitlab.sh /entrypoint_gitlab.sh
COPY entrypoint_github.sh /entrypoint_github.sh
COPY terrat_runner /terrat_runner

COPY proxy/bin /usr/local/proxy/bin

COPY bin/ /usr/local/bin

ENTRYPOINT ["/entrypoint.sh"]
