ARG BASE_IMAGE=ghcr.io/terrateamio/action-base-fips:1790075269@sha256:cd146820ca89c5005c6989217df98ef147254a1e5435a337ab91cba109228591
FROM ${BASE_IMAGE}

COPY entrypoint.sh /entrypoint.sh
COPY entrypoint_gitlab.sh /entrypoint_gitlab.sh
COPY entrypoint_github.sh /entrypoint_github.sh
COPY terrat_runner /terrat_runner

COPY proxy/bin /usr/local/proxy/bin

COPY bin/ /usr/local/bin

ENTRYPOINT ["/entrypoint.sh"]
