name: 'Terrateam Workflow (FIPS)'
description: 'Terraform Automation with GitHub Pull Requests, on the FIPS base image'
inputs:
  work-token:
    description: 'Work token for run'
    required: true
  api-base-url:
    description: 'Base URL to API'
    required: true
    default: 'https://app.terrateam.io'
runs:
  using: 'docker'
  image: 'docker://ghcr.io/terrateamio/action-fips:v1.1.1@sha256:bb342b3ead103dbd0ad167f8fa0714d5f39f416b79c03d85a3a45447619d84be'
  args:
    - '${{ inputs.work-token }}'
    - '${{ inputs.api-base-url }}'
